# Generated by Django 4.2.5 on 2023-09-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('device', '0003_device_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='employee',
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('checked_out_date', models.DateTimeField(auto_now=True)),
                ('returned_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
